Repository ale-sanchez-g/superheroes, pull requests merged in 2020-04, with the labels that each got.

#3 add ci in shippable
  app/test/superheroes.postman_collection.json
  package.json
  shippable.yml
Labels: test

#4 New concept
  README.md
  app/battlefield/bus.json
  app/battlefield/library.json
  app/battlefield/office.json
  app/battlefield/restaurant.json
  app/heroes.js
  app/img/handWasher.jpg
  app/img/soap.jpg
  app/img/social-distance.jpg
  app/img/working-from-home.jpg
  app/test/superheroes.postman_collection.json
Labels: enhancement

#9 Added api v2 endpoint route and added new Json Payload for battlefields
  app/battlefield/v2/bus.json
  app/battlefield/v2/library.json
  app/battlefield/v2/office.json
  app/battlefield/v2/restaurant.json
  app/heroes.js
Labels: enhancement

#13 fix answer
  app/battlefield/v2/office.json
Labels: bug
